name: "🐛 Bug report"
description: Something broken or incorrect
labels: ["bug", "status:needs-triage"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      placeholder: "Short description of the bug"
    validations: { required: true }
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1) Open report link\n2) Go to 'Interactive Table'\n3) Click Download CSV…"
  - type: textarea
    id: expected
    attributes:
      label: Expected vs actual
      placeholder: "Expected: …\nActual: …"
  - type: textarea
    id: env
    attributes:
      label: Device / browser (optional)
      placeholder: "Windows + Chrome 129; Mac + Safari 18"
