name: "📝 Review feedback"
description: Form for reviewers
labels: ["review", "status:needs-triage"]
body:
  - type: input
    id: context
    attributes:
      label: What were you reviewing?
      placeholder: "Example: 'Interactive Map → marker popups'"
  - type: textarea
    id: feedback
    attributes:
      label: Your feedback
      description: Write in plain language—bullets are great.
      placeholder: "What looks good? What’s confusing? What should change?"
    validations: { required: true }
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: Drag & drop images here.
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: ["P1 - must fix", "P2 - should fix", "P3 - nice to have"]
    validations: { required: true }
